CREATE TABLE IF NOT EXISTS comment_data (
    id SERIAL PRIMARY KEY NOT NULL,
    parent_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    body TEXT,
    time TIMESTAMP NOT NULL DEFAULT NOW,
);

CREATE TABLE IF NOT EXISTS post_data (
    id SERIAL PRIMARY KEY NOT NULL,
)
